// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_CHARACTER_JONOONDB_TUTORIAL_H_
#define FLATBUFFERS_GENERATED_CHARACTER_JONOONDB_TUTORIAL_H_

#include "flatbuffers/flatbuffers.h"

namespace jonoondb_tutorial {

struct Character;

enum VitalStatus {
  VitalStatus_Alive = 1,
  VitalStatus_Dead = 2,
  VitalStatus_MIN = VitalStatus_Alive,
  VitalStatus_MAX = VitalStatus_Dead
};

inline const char **EnumNamesVitalStatus() {
  static const char *names[] = { "Alive", "Dead", nullptr };
  return names;
}

inline const char *EnumNameVitalStatus(VitalStatus e) { return EnumNamesVitalStatus()[static_cast<int>(e) - static_cast<int>(VitalStatus_Alive)]; }

struct Character FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_NAME = 4,
    VT_HOUSE = 6,
    VT_STATUS = 8,
    VT_PLAYED_BY = 10,
    VT_AGE_YEARS = 12,
    VT_FIRST_SEEN = 14,
    VT_ALIASES = 16
  };
  const flatbuffers::String *name() const { return GetPointer<const flatbuffers::String *>(VT_NAME); }
  const flatbuffers::String *house() const { return GetPointer<const flatbuffers::String *>(VT_HOUSE); }
  VitalStatus status() const { return static_cast<VitalStatus>(GetField<int8_t>(VT_STATUS, 1)); }
  const flatbuffers::String *played_by() const { return GetPointer<const flatbuffers::String *>(VT_PLAYED_BY); }
  int32_t age_years() const { return GetField<int32_t>(VT_AGE_YEARS, 0); }
  const flatbuffers::String *first_seen() const { return GetPointer<const flatbuffers::String *>(VT_FIRST_SEEN); }
  const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *aliases() const { return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(VT_ALIASES); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_NAME) &&
           verifier.Verify(name()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_HOUSE) &&
           verifier.Verify(house()) &&
           VerifyField<int8_t>(verifier, VT_STATUS) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_PLAYED_BY) &&
           verifier.Verify(played_by()) &&
           VerifyField<int32_t>(verifier, VT_AGE_YEARS) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_FIRST_SEEN) &&
           verifier.Verify(first_seen()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_ALIASES) &&
           verifier.Verify(aliases()) &&
           verifier.VerifyVectorOfStrings(aliases()) &&
           verifier.EndTable();
  }
};

struct CharacterBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_name(flatbuffers::Offset<flatbuffers::String> name) { fbb_.AddOffset(Character::VT_NAME, name); }
  void add_house(flatbuffers::Offset<flatbuffers::String> house) { fbb_.AddOffset(Character::VT_HOUSE, house); }
  void add_status(VitalStatus status) { fbb_.AddElement<int8_t>(Character::VT_STATUS, static_cast<int8_t>(status), 1); }
  void add_played_by(flatbuffers::Offset<flatbuffers::String> played_by) { fbb_.AddOffset(Character::VT_PLAYED_BY, played_by); }
  void add_age_years(int32_t age_years) { fbb_.AddElement<int32_t>(Character::VT_AGE_YEARS, age_years, 0); }
  void add_first_seen(flatbuffers::Offset<flatbuffers::String> first_seen) { fbb_.AddOffset(Character::VT_FIRST_SEEN, first_seen); }
  void add_aliases(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> aliases) { fbb_.AddOffset(Character::VT_ALIASES, aliases); }
  CharacterBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  CharacterBuilder &operator=(const CharacterBuilder &);
  flatbuffers::Offset<Character> Finish() {
    auto o = flatbuffers::Offset<Character>(fbb_.EndTable(start_, 7));
    return o;
  }
};

inline flatbuffers::Offset<Character> CreateCharacter(flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<flatbuffers::String> house = 0,
    VitalStatus status = VitalStatus_Alive,
    flatbuffers::Offset<flatbuffers::String> played_by = 0,
    int32_t age_years = 0,
    flatbuffers::Offset<flatbuffers::String> first_seen = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> aliases = 0) {
  CharacterBuilder builder_(_fbb);
  builder_.add_aliases(aliases);
  builder_.add_first_seen(first_seen);
  builder_.add_age_years(age_years);
  builder_.add_played_by(played_by);
  builder_.add_house(house);
  builder_.add_name(name);
  builder_.add_status(status);
  return builder_.Finish();
}

inline flatbuffers::Offset<Character> CreateCharacterDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const char *house = nullptr,
    VitalStatus status = VitalStatus_Alive,
    const char *played_by = nullptr,
    int32_t age_years = 0,
    const char *first_seen = nullptr,
    const std::vector<flatbuffers::Offset<flatbuffers::String>> *aliases = nullptr) {
  return CreateCharacter(_fbb, name ? _fbb.CreateString(name) : 0, house ? _fbb.CreateString(house) : 0, status, played_by ? _fbb.CreateString(played_by) : 0, age_years, first_seen ? _fbb.CreateString(first_seen) : 0, aliases ? _fbb.CreateVector<flatbuffers::Offset<flatbuffers::String>>(*aliases) : 0);
}

inline const jonoondb_tutorial::Character *GetCharacter(const void *buf) { return flatbuffers::GetRoot<jonoondb_tutorial::Character>(buf); }

inline bool VerifyCharacterBuffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<jonoondb_tutorial::Character>(nullptr); }

inline const char *CharacterExtension() { return "bfbs"; }

inline void FinishCharacterBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<jonoondb_tutorial::Character> root) { fbb.Finish(root); }

}  // namespace jonoondb_tutorial

#endif  // FLATBUFFERS_GENERATED_CHARACTER_JONOONDB_TUTORIAL_H_
